name: Test
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version from the tag
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//
    - name: Deploy Ansible Galaxy Collection
      uses: docker://artis3n/ansible_galaxy_collection:v2.2.0
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
        collection_dir: ansible_collections/test/test
        galaxy_version: '${{ env.RELEASE_VERSION }}'
