name: Test
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@a57a806e2b1abffa509289818531d11948bce744
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
        collection_dir: ansible_collections/test/test
