name: Test
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@e0d92244431c0bfa87195a4c097667b4fc900ceb
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
        collection_dir: ansible_collections/test/test
